### ISSUE TITLE
Feature: Incremental Parsing

### ISSUE THREAD

**Issue by jjl** [plataformatec/nimble_parsec#32] opened 2018-07-21 12:38 UTC
It would be nice to be able to stream data into nimble_parsec as it arrives over the network.

Current Support: None (as far as I can tell)

Things to consider:
* Not every user requires this and supporting it where it's not needed would have performance implications, so it should probably become a `defparsec` option
* Doneness is not always decidable in incremental mode

**Comment by josevalim** [comment] 2018-07-21 15:06
@jjl the issue is that we heavily inline code `nimble_parsec`. So for example, the datetime parser in the readme, when given something like "2010-04-17T" will return an error while it is just incomplete, since we attempt to match everything or nothing at all. So basically, you'd need to track completion on the side, because you simply can't rely on `nimble_parsec` to do that.

I wouldn't oppose if the `:error` tuple returns a new element, which is an anonymous function representing the parsing stack. This anonymous function can be invoked again with a binary to resume parsing. This should be cheap enough so we can always do it without hiding it behind an option.

Then we need tests for each combinator. Once this is done, it should be good for merging. A PR is appreciated.

Thanks!

**Comment by josevalim** [comment] 2018-08-10 16:14
Ping?

**Comment by josevalim** [comment] 2019-05-18 12:12
Closing this for now.

**Closed by josevalim** 2019-05-18 12:12 UTC
